- README.md
- build.gradle
- src/main/resources/META-INF/plugin.xml
> release 0.1.5

- build.gradle
- src/main/resources/META-INF/plugin.xml
> support version 191.* build of intellij

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntention.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntentionTest.kt
```kotlin
data class Address(val zipCode: String)
data class User(
val name: String,
val age: Int,
val address: Address
)
val user = User()
```
to
```kotlin
data class Address(val zipCode: String)
data class User(
val name: String,
val age: Int,
val address: Address
)
val user = User(name = "", age = 0, address = Address(zipCode = ""))
```
> Support non primitive types

- build.gradle
> Fix tests for idea 2019.2

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntention.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntentionTest.kt
> Fixes #26 #27 #28

- build.gradle
> Add support for 2019.3

- build.gradle
Closes #36
This was inspired by the work done in #31
> Add support for 2021.1

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntention.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/intentions/FillClassIntentionTest.kt
> Suggest in super type call entry

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspection.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspectionTest.kt
> Add default value to lambda arguments

- build.gradle
- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspectionTest.kt
Also reformats FillClassInspectionTest.kt with ktlint
Closes #63
> Add "trailing comma" setting

- README.md
Replace the existing Thanks section to an auto-generated image as I can't keep updating that section 😓
> replace thanks to auto generated one

- README.md
Happy to introduce @oboenikui as a new maintainer of kotlin-fill-class🎉 
He is my former colleague and also an active user of this plugin.
He'll help me triage issues, review PRs, and release a new version from now on! This would significantly reduce the time to fix bugs and ship new features for this plugin(no more late replies from me 😅 )
> add new maintainer @oboenikui

- build.gradle
- src/main/resources/META-INF/plugin.xml
A few minor adjustments (see commits list). Requires #64 to be merged first.
Actual diff: https://github.com/rock3r/kotlin-fill-class/compare/trailing-comma...rock3r:cleanup
> Cleanup plugin.xml and Gradle

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspection.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspectionTest.kt
> Do not add unnecessary trailing comma

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspection.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspectionTest.kt
> Fix false negative for imported extension function calls

- build.gradle
- src/main/resources/META-INF/plugin.xml
close #71
I've checked with `223.7571.58-EAP-SNAPSHOT`.
> add support 2022.3 and future versions

- DEPLOYING.md
Added `DEPLOYING.md` to explain how to publish a new version, mainly for @oboenikui and future maintainers 🙏
> add a doc to explain how to publish new version

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspection.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillClassInspectionTest.kt
> Don't fill duplicated lambda argument

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/helper/PutArgumentOnSeparateLineHelper.kt
- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/BaseFillClassInspection.kt
- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillDummyValuesInspection.kt
- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillEmptyValuesInspection.kt
With reflection, now supports both `org.jetbrains.kotlin.idea.intentions.ChopArgumentListIntention` and `org.jetbrains.kotlin.idea.codeInsight.intentions.shared.ChopArgumentListIntention`.
close #91
> #91 Update ChopArgumentListIntention package for IDEA 2023.1

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/BaseFillClassInspection.kt
> preview put argument on separate lines correctly

- src/main/kotlin/com/github/suusan2go/kotlinfillclass/inspections/BaseFillClassInspection.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillDummyValueInspectionTest.kt
- src/test/kotlin/com/github/suusan2go/kotlinfillclass/inspections/FillEmptyValueInspectionTest.kt
> fix trailing comma with trailing lambda
